base_url = "https://example.com"

title = "Yizhe's Notebook"

compile_sass = true

build_search_index = false

theme = "anpu"

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true

[extra]
# anpu_menu_links = [{ url = "$BASE_URL/about/", name = "About" }]
